-- Hotfix for Phase2 ID column length mismatch (UUID is 36 chars)

ALTER TABLE mall_idempotency
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL,
  MODIFY COLUMN idempotency_key VARCHAR(128) NOT NULL,
  MODIFY COLUMN biz_id VARCHAR(64) NULL;

ALTER TABLE mall_payment
  MODIFY COLUMN id VARCHAR(64) NOT NULL,
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL,
  MODIFY COLUMN order_id VARCHAR(64) NOT NULL;

ALTER TABLE mall_after_sales
  MODIFY COLUMN id VARCHAR(64) NOT NULL,
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL,
  MODIFY COLUMN order_id VARCHAR(64) NOT NULL,
  MODIFY COLUMN payment_id VARCHAR(64) NULL;
